// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type CreateCommentInput struct {
	Comment        string  `json:"comment"`
	PostID         string  `json:"postId"`
	ReplyToComment *string `json:"replyToComment"`
}

type CreatePostInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Hashtag     string `json:"hashtag"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type PostFilterInput struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type PostResponse struct {
	TotalPost *int    `json:"totalPost"`
	Post      []*Post `json:"post"`
}

type RegisterInput struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type UserQueryInput struct {
	ID       *string `json:"ID"`
	Username *string `json:"username"`
}
