// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type CreateCommentInput struct {
	Comment        string  `json:"comment"`
	PostID         string  `json:"postId"`
	ReplyToComment *string `json:"replyToComment"`
}

type CreatePostInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Hashtag     string `json:"hashtag"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterInput struct {
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type UserQueryInput struct {
	ID    *string `json:"ID"`
	Email *string `json:"email"`
}
